### ISSUE TITLE
fresh install of ruby dev and weblink installs but does not start

### ISSUE THREAD

**Issue by rimrad** [soylent/weblink#1]
this is what i get when i try to start weblink;

C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/weblink-1.1.0/lib/weblink.rb:22:in `block in start': undefined method `ipv4_private?' for nil:NilClass (NoMethodError)

      ip = Socket.getifaddrs.find { |ifa| ifa.addr.ipv4_private? }
                                                  ^^^^^^^^^^^^^^
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/weblink-1.1.0/lib/weblink.rb:22:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/weblink-1.1.0/lib/weblink.rb:22:in `find'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/weblink-1.1.0/lib/weblink.rb:22:in `start'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/weblink-1.1.0/bin/weblink:79:in `<top (required)>'
        from C:/Ruby31-x64/bin/weblink:25:in `load'
        from C:/Ruby31-x64/bin/weblink:25:in `<main>'

**Comment by soylent** [comment]
Thank you, @rimrad! Could you also post the output of `ruby -rsocket -e 'pp Socket.getifaddrs.map { [_1, _1.addr] }'` please?

**Comment by rimrad** [comment]
this is what i get;

[[#<Socket::Ifaddr ethernet_32769>, nil],
 [#<Socket::Ifaddr wireless_32769>, nil],
 [#<Socket::Ifaddr wireless_32770>, nil],
 [#<Socket::Ifaddr wireless_32768 UP 2607:fb90:f368:6db4:345c:d97d:f67c:fe05>,
  #<Addrinfo: 2607:fb90:f368:6db4:345c:d97d:f67c:fe05>],
 [#<Socket::Ifaddr wireless_32768 UP 2607:fb90:f368:6db4:2c34:5c89:84e4:2608>,
  #<Addrinfo: 2607:fb90:f368:6db4:2c34:5c89:84e4:2608>],
 [#<Socket::Ifaddr wireless_32768 UP fe80::345c:d97d:f67c:fe05%11>, #<Addrinfo: fe80::345c:d97d:f67c:fe05%11>],
 [#<Socket::Ifaddr wireless_32768 UP 172.20.10.2>, #<Addrinfo: 172.20.10.2>],
 [#<Socket::Ifaddr ethernet_32774>, nil],
 [#<Socket::Ifaddr loopback_0 UP,LOOPBACK ::1>, #<Addrinfo: ::1>],
 [#<Socket::Ifaddr loopback_0 UP,LOOPBACK 127.0.0.1>, #<Addrinfo: 127.0.0.1>]]

**Comment by soylent** [comment]
Thanks, @rimrad! I've released a new version of weblink (v1.1.1). Please give it a try:
```sh
gem update weblink

weblink --version  # You should see "1.1.1"
```

**Comment by soylent** [comment]
Hi @rimrad I've just fixed another bug that probably affected you too. A new version of weblink is available:
```sh
$ gem update weblink
$ weblink --version  # this should print v1.1.2
```
